import { Property } from "./types";

export const dummyProperties: Property[] = [
  {
    id: "1",
    title: "Modern Apartment in Downtown",
    price: 350000,
    location: "New York, NY",
    specs: { beds: 2, baths: 2, area: 1200 },
    images: ["https://via.placeholder.com/400x300?text=Apartment+1"],
    status: "available",
  },
  {
    id: "2",
    title: "Cozy Suburban House",
    price: 250000,
    location: "Los Angeles, CA",
    specs: { beds: 3, baths: 2, area: 1500 },
    images: ["https://via.placeholder.com/400x300?text=House+2"],
    status: "sold",
  },
  {
    id: "3",
    title: "Luxury Villa with Pool",
    price: 850000,
    location: "Miami, FL",
    specs: { beds: 5, baths: 4, area: 3000 },
    images: ["https://via.placeholder.com/400x300?text=Villa+3"],
    status: "available",
  },
  {
    id: "4",
    title: "Spacious Loft in San Francisco",
    price: 500000,
    location: "San Francisco, CA",
    specs: { beds: 2, baths: 1, area: 900 },
    images: ["https://via.placeholder.com/400x300?text=Loft+4"],
    status: "pending",
  },
  {
    id: "5",
    title: "Beachfront Condo",
    price: 600000,
    location: "Santa Monica, CA",
    specs: { beds: 3, baths: 2, area: 1400 },
    images: ["https://via.placeholder.com/400x300?text=Condo+5"],
    status: "available",
  },
  {
    id: "6",
    title: "Urban Studio Apartment",
    price: 200000,
    location: "Chicago, IL",
    specs: { beds: 1, baths: 1, area: 700 },
    images: ["https://via.placeholder.com/400x300?text=Studio+6"],
    status: "available",
  },
  {
    id: "7",
    title: "Historic Townhouse",
    price: 450000,
    location: "Boston, MA",
    specs: { beds: 4, baths: 3, area: 2200 },
    images: ["https://via.placeholder.com/400x300?text=Townhouse+7"],
    status: "sold",
  },
  {
    id: "8",
    title: "Countryside Farmhouse",
    price: 300000,
    location: "Austin, TX",
    specs: { beds: 3, baths: 2, area: 1800 },
    images: ["https://via.placeholder.com/400x300?text=Farmhouse+8"],
    status: "available",
  },
  {
    id: "9",
    title: "Penthouse with City Views",
    price: 1200000,
    location: "Seattle, WA",
    specs: { beds: 3, baths: 3, area: 2500 },
    images: ["https://via.placeholder.com/400x300?text=Penthouse+9"],
    status: "available",
  },
  {
    id: "10",
    title: "Lakefront Cottage",
    price: 400000,
    location: "Orlando, FL",
    specs: { beds: 2, baths: 1, area: 1100 },
    images: ["https://via.placeholder.com/400x300?text=Cottage+10"],
    status: "pending",
  },
  {
    id: "11",
    title: "Rustic Cabin in the Woods",
    price: 200000,
    location: "Asheville, NC",
    specs: { beds: 2, baths: 1, area: 800 },
    images: ["https://via.placeholder.com/400x300?text=Cabin+11"],
    status: "available",
  },
  {
    id: "12",
    title: "Victorian Mansion",
    price: 1000000,
    location: "Savannah, GA",
    specs: { beds: 6, baths: 5, area: 5000 },
    images: ["https://via.placeholder.com/400x300?text=Mansion+12"],
    status: "sold",
  },
  {
    id: "13",
    title: "Eco-Friendly Tiny House",
    price: 100000,
    location: "Portland, OR",
    specs: { beds: 1, baths: 1, area: 400 },
    images: ["https://via.placeholder.com/400x300?text=Tiny+13"],
    status: "available",
  },
  {
    id: "14",
    title: "Suburban Split-Level Home",
    price: 320000,
    location: "Denver, CO",
    specs: { beds: 3, baths: 2, area: 1600 },
    images: ["https://via.placeholder.com/400x300?text=Home+14"],
    status: "available",
  },
  {
    id: "15",
    title: "Industrial-Style Condo",
    price: 400000,
    location: "Brooklyn, NY",
    specs: { beds: 2, baths: 2, area: 1200 },
    images: ["https://via.placeholder.com/400x300?text=Condo+15"],
    status: "pending",
  },
  {
    id: "16",
    title: "Mediterranean Villa",
    price: 900000,
    location: "Los Angeles, CA",
    specs: { beds: 4, baths: 3, area: 3200 },
    images: ["https://via.placeholder.com/400x300?text=Villa+16"],
    status: "available",
  },
  {
    id: "17",
    title: "Mid-Century Modern Home",
    price: 550000,
    location: "Palm Springs, CA",
    specs: { beds: 3, baths: 2, area: 2000 },
    images: ["https://via.placeholder.com/400x300?text=Home+17"],
    status: "available",
  },
  {
    id: "18",
    title: "Ski Chalet",
    price: 750000,
    location: "Aspen, CO",
    specs: { beds: 5, baths: 4, area: 3500 },
    images: ["https://via.placeholder.com/400x300?text=Chalet+18"],
    status: "sold",
  },
  {
    id: "19",
    title: "City Center Apartment",
    price: 300000,
    location: "Atlanta, GA",
    specs: { beds: 2, baths: 2, area: 1000 },
    images: ["https://via.placeholder.com/400x300?text=Apartment+19"],
    status: "available",
  },
  {
    id: "20",
    title: "Coastal Beach House",
    price: 800000,
    location: "Myrtle Beach, SC",
    specs: { beds: 4, baths: 3, area: 2800 },
    images: ["https://via.placeholder.com/400x300?text=BeachHouse+20"],
    status: "available",
  },
];
