import type { Metadata } from "next";
import "./globals.css";
// app/layout.tsx
import Header from "../components/server/PropertySearch"; // Add search component here
import Footer from "../components/server/Footer"; // Create footer component later

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Property Listing Platform" />
        <title>Property Listing Platform</title>
      </head>

      <body className="font-sans bg-gray-50">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
